export const REMOVE_TODO_BY_ID = 'REMOVE_TODO_BY_ID';

export const EDIT_LAST_TODO = 'EDIT_LAST_TODO';

export const EDIT_TODO_BY_ID = 'EDIT_TODO_BY_ID';

export const TODO_TO_INPROGRESS = 'TODO_TO_INPROGRESS';

export const INPROGRESS_TO_TODO = 'INPROGRESS_TO_TODO';

export const INPROGRESS_TO_DONE = 'INPROGRESS_TO_DONE';

export const DONE_TO_INPROGRESS = 'DONE_TO_INPROGRESS';